-- 初始化所有微服务数据库

-- 创建数据库
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS asset_db;
CREATE DATABASE IF NOT EXISTS alert_db;
CREATE DATABASE IF NOT EXISTS report_db;
CREATE DATABASE IF NOT EXISTS notify_db;
CREATE DATABASE IF NOT EXISTS probe_db;
CREATE DATABASE IF NOT EXISTS intel_db;

-- 显示所有数据库
\l
